### ISSUE TITLE
running eval.py without tfrecords

### ISSUE THREAD

**Issue by sbharadwajj** [ivclab/agegenderLMTCNN#1]
@Jia-HongHenryLee is it possible to run the evaluation for images(jpg/png) instead of tfrecords?

**Comment by Jia-HongHenryLee** [comment]
@chichilicious  Yes, it can. but I need to prepare my codes after finishing other project.
wait me two weeks. Thank you very much.

**Comment by sbharadwajj** [comment]
@Jia-HongHenryLee Hi, I'm trying to run inference for this using rude-carnie's implementation. But i'm getting an error wrt checkpoint. which checkpoint file should i exactly use?
Error:
NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

```
Key InceptionV3/Conv2d_1a_3x3/BatchNorm/beta not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
	 [[Node: save/RestoreV2/_301 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_306_save/RestoreV2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

```
I'm running this from my terminal:
`python test.py --model_type inception --model_dir models/train_val_test_per_fold_agegender/test_fold_is_0/LMTCNN-1-1-run-30707/checkpoint-49 --filename /age_gender/inputs/DSC_0471.JPG.jpg
`
Should i change the model_type or is it not possible to run inference without the frozen .pb file?

**Comment by Jia-HongHenryLee** [comment]
@chichilicious  hello, please follow my .sh file in script directory. Thank you very much. I don't train model which network structure is inception type. In my model.py file, I provide the inception and mobilenet_v1 structure, so you can try to train this network structure by yourself. If you have the problem, you can ask me. Thank you very much.

**Comment by Jia-HongHenryLee** [comment]
@chichilicious  I add inference.py which can evaluate facial image.
