### ISSUE TITLE
model size 

### ISSUE THREAD

**Issue by pribadihcr** [ivclab/agegenderLMTCNN#3]
Hi, I download the model.zip,

Look like the LMTCNN-2-1 model size is around 60MB, but in a paper it  reported 30MB

Thanks

**Comment by Jia-HongHenryLee** [comment]
@pribadihcr  it's because that this is the model size of .pb file which is a frozen model in the paper.
I will upgrade the models in next week. Thank you very much.

**Comment by Jia-HongHenryLee** [comment]
@pribadihcr  I finish to upgrade the models.
